---
# tasks file for app-cryosparc

- name: Install prerequisite dependencies
  package:
    name: curl
    state: present

- name: Include user creation tasks
  include_tasks: user.yml

# We install the worker first for cluster configurations.
# This ensures that the situation where the master and a cluster node are the same node are supported.
- name: Include worker node installation tasks
  include_tasks: worker.yml
  when: "'worker' in cryosparc_roles and 'cluster' in cryosparc_roles and cryosparc_cluster"

- name: Include master node installation tasks
  include_tasks: master.yml
  when: "'master' in cryosparc_roles"

- name: Include worker node installation tasks
  include_tasks: worker.yml
  when: "'worker' in cryosparc_roles and not cryosparc_cluster"
